# Generated by Django 3.0.6 on 2020-05-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val1', models.FloatField()),
                ('val2', models.FloatField()),
                ('oper', models.CharField(choices=[('+', 'Soma'), ('-', 'Subtração'), ('*', 'Multiplicação'), ('/', 'Divisão')], max_length=1)),
            ],
        ),
    ]
